### ISSUE TITLE
404 dans les liens des réponses

### ISSUE THREAD

**Issue by AntoineAugusti** [bzg/covid19-faq-data#1]
Sur [cet article](https://practical-pasteur-83aa55.netlify.app/#?faq=64) les liens externes ont comme base ton domaine et non le domaine tiers, ce qui entraine une 404

**Comment by bzg** [comment]
Oui, j'ai vu ça, je vais tenter de corriger. Merci  !

**Comment by bzg** [comment]
Désolé pour le délai, ça devrait être corrigé - tu peux tester l'ensemble des +1000 questions/réponses [ici](https://practical-pasteur-83aa55.netlify.app).
